gText_FlyingTaxi_Unavailable::
    .string "Unfortunately the FLYING TAXI\n"
    .string "SERVICE is unavailable.$"

gText_FlyingTaxi_FirstUse::
    .string "Hello there.\n"
	.string "What's your name?\p"
	.string "Okay, your name's {PLAYER}{KUN}.\n"
    .string "It's nice to meet you!\p"
    .string "I'm a pilot from the FLYING TAXI\n"
    .string "SERVICE, that means I can you take to\l"
    .string "anyplace you've been before.\p"
    .string "So with that being said and done…\n"
    .string "Would you like to travel somewhere?$"

gText_FlyingTaxi_Available::
    .string "Hello {PLAYER}!\p"
	.string "Would you like to travel somewhere\n"
	.string "using the FLYING TAXI SERVICE?$"

gText_FlyingTaxi_WhereToGo::
    .string "Where would you like to go?$"

gText_FlyingTaxi_Goodbye::
    .string "Keep us in mind the next time\n"
    .string "you need a ride!$"
